- hosts: 127.0.0.1

  tasks:
  - name: show
    command: ifconfig -a
    register: interfaces

  - name: set_fact
    set_fact:
      packets: "{{ interfaces['stdout'] | regex_findall('RX packets:([0-9]+)') }}"

  - name: show results
    debug:
      msg: "{{ packets | map('int') | sum }}"